FROM apache/airflow:2.6.3

# Use o usuário airflow para instalar pacotes
USER airflow

# Instalar bibliotecas adicionais necessárias
RUN pip install --no-cache-dir pandas matplotlib requests openpyxl numpy

